# Generated by Django 3.0.4 on 2020-07-29 09:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='user-basic.png', upload_to=accounts.models.user_path),
        ),
        migrations.AlterField(
            model_name='friendgroup',
            name='profile_image',
            field=models.ImageField(default='group-basic.png', upload_to=accounts.models.user_group_path),
        ),
    ]
