# Generated by Django 3.0.4 on 2020-06-24 19:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200323_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='brthyear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='user_basic.png', upload_to=accounts.models.user_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('custom', 'Custom'), ('unknwon', 'Unknwon')], default='unknwon', max_length=7),
        ),
    ]
