# Generated by Django 3.0.4 on 2020-06-24 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200624_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=16)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendGroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendOf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account_id', 'friend_id')},
            },
        ),
        migrations.CreateModel(
            name='Relationship_FriendGroup_MAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='accounts.FriendGroup')),
                ('relationship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.Relationship')),
            ],
            options={
                'unique_together': {('group_id', 'relationship_id')},
            },
        ),
    ]
