# Generated by Django 3.0.4 on 2020-06-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_friendgroup_relationship_relationship_friendgroup_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendgroup',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='relationship_friendgroup_map',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='relationship_friendgroup_map',
            old_name='relationship_id',
            new_name='relationship',
        ),
    ]
