# Generated by Django 3.0.4 on 2020-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200624_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='dispatch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_friend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='relationship_friendgroup_map',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('account', 'friend'), name='af_compositeKey'),
        ),
        migrations.AddConstraint(
            model_name='relationship_friendgroup_map',
            constraint=models.UniqueConstraint(fields=('group', 'relationship'), name='gr_compositeKey'),
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='is_blocked',
        ),
    ]
