# Generated by Django 3.0.4 on 2020-07-13 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200630_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
