# Generated by Django 3.0.4 on 2020-07-13 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_relationship_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship_friendgroup_map',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
