# Generated by Django 3.0.4 on 2020-07-13 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_relationship_friendgroup_map_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='friendgroup',
            constraint=models.UniqueConstraint(fields=('account', 'group_name'), name='group_name_unique'),
        ),
    ]
