# Generated by Django 3.0.4 on 2020-07-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200713_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendgroup',
            old_name='group_name',
            new_name='groupname',
        ),
    ]
