# Generated by Django 3.0.4 on 2020-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200714_0041'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendgroup',
            name='group_name_unique',
        ),
        migrations.AddConstraint(
            model_name='friendgroup',
            constraint=models.UniqueConstraint(fields=('account', 'groupname'), name='group_name_unique'),
        ),
    ]
