# Generated by Django 3.0.4 on 2020-07-14 00:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200714_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendgroup',
            name='profile_image',
            field=models.ImageField(default='group_basic.png', upload_to=accounts.models.user_group_path),
        ),
    ]
