# Generated by Django 3.0.4 on 2020-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_friendgroup_profile_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationship',
            name='af_compositeKey',
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('account_id', 'friend_id'), name='af_compositeKey'),
        ),
    ]
