# Generated by Django 3.0.2 on 2020-02-01 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('CLOSED', 'Closed'), ('OPEN', 'Open'), ('PENDING', 'Pending')], default='OPEN', max_length=50, null=True)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('guests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Invitation',
            },
        ),
    ]
