# Generated by Django 3.0.2 on 2020-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='host',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
