# Generated by Django 3.0.4 on 2020-06-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='photos/no_image.png', upload_to='photos/events/%Y%m%d'),
        ),
    ]
