# Generated by Django 3.0.4 on 2020-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20200730_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
