# Generated by Django 3.0.4 on 2020-06-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20200624_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='guest',
        ),
    ]
