# Generated by Django 3.0.4 on 2020-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20200624_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='attendance',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('Waiting for a response', 'Unknown')], default='Waiting for a response', max_length=25),
        ),
    ]
